name: Patch and Build

on:
  push:
    branches: [ "main" ]

jobs:
  compile_1_21_5_core_jar:
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        
      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
        
      - name: Apply Patches
        run: ./gradlew applyAllPatches
   
      - name: Build Jar
        run: ./gradlew createMojmapPaperclipJar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: canvas-paperclip-1.21.5-R0.1-SNAPSHOT-mojmap.jar
          path: canvas-server/build/libs/canvas-paperclip-1.21.5-R0.1-SNAPSHOT-mojmap.jar
          retention-days: 1
