name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Server
        run: |
          ./gradlew clean cleanCache
          ./gradlew applyPatches --no-daemon
          ./gradlew createCanvasServer --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-jar
          path: 'build/libs/*.jar'
          retention-days: 1
